# DISPLAY
## set prompt to display only the colored current directory
    time="33m`date +%H:%M`"
    time1="\[\033[$time\]"
    dir1="\[\033[37m\]\w\[\033[00m\]"
    PS1="$dir1\$ "
## unbolded colored directories in "ls" command
    LS_COLORS=$LS_COLORS:'di=0;94:'
    export LS_COLORS

# PATHS
    export EDITOR="/usr/bin/vim"
    export SUDO_EDITOR="/usr/bin/vim"
    PATH=/usr/local/texlive/2023/bin/x86_64-linux:$PATH
    export GOPATH=$HOME/.go

# API
    source $HOME/files/sec/API
    export OPENAI_API_KEY=$OPENAI_API_KEY
    export DEVTO_TOKEN=$DEVTO_TOKEN

# COMPLETION
    complete -C '/usr/bin/aws_completer' aws

# ADDITIONAL FILES
    source $HOME/files/config/linux/bash/bashrc_aliases
    source $HOME/files/config/linux/bash/bashrc_functions
    source $HOME/files/config/linux/bash/bashrc_vim
    source $HOME/files/config/linux/bash/bashrc_includes

## Auxiliary Data
    declare -a SR_escapes
    SR_espapes[0]="\\"
    SR_espapes[1]="&"
    SR_espapes[2]="/"
    SR_espapes[3]="$"
    SR_espapes[4]="["
    SR_espapes[5]="]"
    SR_espapes[6]="("
    SR_espapes[7]=")"
    SR_espapes[8]="*"
    SR_espapes[9]="+"
    SR_espapes[10]="."
    SR_espapes[11]="?"
    SR_espapes[12]="|"
    SR_espapes[13]="^"
    SR_espapes[14]="!"
    SR_espapes[15]="\'"
    SR_espapes[16]="\""
    SR_espapes[17]="\`"

## Auxiliary Functions
    function SR_escape(){
        escaped="$1"
        for i in ${!SR_escapes[@]}; do
            escaped=$(echo $escaped | sed "s/${SR_escapes[$i]}/\\${SR_escapes[$i]}")
        done
        echo "$escaped"
    } 
