#! /bin/bash

# API
source $HOME/files/sec/API
export OPENAI_API_KEY=$OPENAI_API_KEY

# WEB PAGES
## "ff" to open "Firefox" in background
    function ff(){
            firefox -p apps -url=$1 & disown && exit
            }
## meet in jtsi
    alias jitsi="firefox -p apps https://meet.jit.si/ & disown && exit"
## meet with hugo
    alias hugo="firefox -p apps https://meet.google.com/zbb-xsxg-swe & disown && exit"
## open tabela de gastos
    alias gastos="firefox -p apps https://docs.google.com/spreadsheets/d/1HRt9HyZ2DzIhvQSjz5hoKAcsdbZmEZoaQwA52BtK5Gs/edit#gid=1739762735 & disown && exit"
    alias gast="gastos"
## open estante virtual
    alias estante="firefox -p apps -url=https://www.estantevirtual.com.br/login & disown && exit"
## open poem website
    alias insensatez="firefox -p apps -url=https://insensatarigidez.com & disown && exit"
    alias insen="insensatez"
## open personal website
    alias yxm="firefox -p apps -url=https://yxmartins.me & disown && exit"
## open whatsapp
    alias whats="firefox -p apps -url=web.whatsapp.com & disown && exit"
## open spotify
    alias spotify="firefox -p apps -url=https://open.spotify.com/?nd=1 & disown && exit"
    alias spt="spotify"
## open discord
    alias disc="firefox -p apps -url=https://discord.com/channels/ & disown && exit"
## open canva
    alias canva="firefox -p light -url=https://www.canva.com/ & disown && exit"
## open instagram
    alias insta="firefox -p light --new-window https://www.instagram.com/insensatarigidez/ & disown && exit"
## open linkedin
    alias linkedin="firefox -p apps -url=https://www.linkedin.com/login & disown && exit"
    alias lnkd="linkedin"
## open jsfiddle
    alias jsf="firefox -p light -url=https://jsfiddle.net & disown && exit"
## open codeberg
    alias codeberg="firefox -p apps -url=https://codeberg.org/user/login & disown && exit"
    alias codeb="codeberg"
    alias cdg="codeberg"
    alias cdb="codeberg"
## open github
    alias github="firefox -p apps -url=https://www.github.com/login & disown && exit"
## open IBM certification courses
    function ibm(){
        if [[ "$1" == "1" ]]; then
            firefox -p apps https://www.coursera.org/learn/introduction-to-cloud/home/week/1  & disown && exit
        elif [[ "$1" == "2" ]]; then
            firefox -p apps https://www.coursera.org/learn/introduction-to-web-development-with-html-css-javacript/home/week/1  & disown && exit
        elif [[ "$1" == "3" ]]; then
            firefox -p apps https://www.coursera.org/learn/getting-started-with-git-and-github/home/week/1  & disown && exit
        elif [[ "$1" == "4" ]]; then
            firefox -p apps https://www.coursera.org/learn/developing-frontend-apps-with-react/home/week/1  & disown && exit
        elif [[ "$1" == "5" ]]; then
            firefox -p apps https://www.coursera.org/learn/developing-backend-apps-with-nodejs-and-express/home/week/1  & disown && exit
        elif [[ "$1" == "6" ]]; then
            firefox -p apps https://www.coursera.org/learn/python-for-applied-data-science-ai/home/week/1  & disown && exit
        elif [[ "$1" == "7" ]]; then
            firefox -p apps https://www.coursera.org/learn/python-project-for-ai-application-development/home/week/1  & disown && exit
        elif [[ "$1" == "8" ]]; then
            firefox -p apps https://www.coursera.org/learn/developing-applications-with-sql-databases-and-django/home/week/1  & disown && exit
        elif [[ "$1" == "9" ]]; then
            firefox -p apps https://www.coursera.org/learn/ibm-containers-docker-kubernetes-openshift/home/week/1  & disown && exit
        elif [[ "$1" == "10" ]]; then
            firefox -p apps https://www.coursera.org/learn/applications-development-microservices-serverless-o\penshift/home/week/1  & disown && exit
        elif [[ "$1" == "11" ]]; then
            firefox -p apps 
        elif [[ "$1" == "12" ]]; then
            firefox -p apps
        else
            echo "option not defined."
        fi
    }
    alias IBM="ibm"

# Vim ALIASES
## "config" function to open config files
    function config(){
        config_dir=~/files/config/
        declare -a config_dirs
        if [[ -z "$1" ]]; then
            vim $config_dir
        elif [[ -n $1 ]] && [[ -z $2 ]]; then
            vim $config_dir/$1
        elif [[ -n $1 ]] && [[ -n $2 ]]; then
            vim $config_dir/$1/$2
        else
            echo "There is no such kind of config."
        fi
    }
    alias cfg="config"
    alias c="config"

## "lec" function to open lec files
    function lec(){
        lec_dir=~/files/nerd/doc/lec/
        declare -a lec_dirs
        lec_dirs=$(find $lec_dir -type d -printf "%f\n")
        if [[ "${lec_dirs[@]}" =~ "$1" ]]; then
            vim $lec_dir/$1
        elif [[ -z "$1" ]]; then
            vim $lec_dir
        else
            echo "There is no such kind of lec."
        fi
    }
## "QA" function to open QA files
    function QA(){
        QA_dir=~/files/nerd/doc/doc/QA
        declare -a QA_dirs
        QA_dirs=$(find $QA_dir -type d -printf "%f\n")
        if [[ "${QA_dirs[@]}" =~ "$1" ]]; then
            vim $QA_dir/$1
        elif [[ -z "$1" ]]; then
            vim $QA_dir
        else
            echo "There is no such kind of QA."
        fi
    }
## "dev" function to open dev files
    function dev(){
        dev_dir=~/files/nerd/dev/
        declare -a dev_dirs
        dev_dirs=$(find $dev_dir -type d -printf "%f\n")
        if [[ "${dev_dirs[@]}" =~ "$1" ]]; then
            vim $dev_dir/$1
        elif [[ -z "$1" ]]; then
            vim $dev_dir
        else
            echo "There is no such kind of dev."
        fi
    }
## "snip" function to open .snippet files
    function snip(){
        snip_dir=~/files/config/vim/bundle/vim-snipmate/snippets
        declare -a snipfiles
        snip_files=$(find $snip_dir -type f -exec basename -s '.snippets' {} +)
        if [[ -z "$1" ]]; then
            vim $snip_dir
        elif [[ "${snip_files[@]}" =~ "$1" ]]; then
            vim $snip_dir/$1.snippets
        else
            echo "There is no such kind of snipt."
        fi
    }
## "ghb" function to open github README.md files
    function ghb(){
        ghb_dir=$HOME/bkp/github
        if [[ -z $1 ]]; then
            vim $ghb_dir
        elif [[ -n $1 ]] && [[ -z $2 ]]; then 
            vim $ghb_dir/$1/README.md
        elif [[ -n $1 ]] && [[ -n $2 ]]; then
            vim $ghb_dir/$1/$2/README.md
        fi
    }
## "cv" function to open curriculum files
    function cv(){
        cv_dir=$HOME/files/nerd/cv
        if [[ -z "$1" ]]; then
            vim $cv_dir
        elif [[ "$1" = "res" ]] || [[ "$1" = "-r" ]]; then
            vim $cv_dir/yxm-cv.md
        elif [[ "$1" = "dev" ]] || [[ "$1" = "-d" ]]; then
            if [[ "$2" == "pt" ]] || [[ "$2" == "-pt" ]]; then
                vim $cv_dir/yxm-dev-pt.md
            elif [[ "$2" == "en" ]] || [[ "$2" == "-en" ]]; then
                vim $cv_dir/yxm-dev-en.md
            else
                echo "option not defined."
            fi
        else
            echo -e -n "
Try \"cv option argument\" 

* option = -r, res; -d, -dev
* argument = -pt, pt; -en, en.

"
        fi
    }
## "org" to open the organization central
    alias org="vim ~/files/org/index.md"
## "settings" or "sets" to open settings file
    alias settings="vim ~/files/nerd/doc/doc/settings/index.md"
    alias sets="settings"
## "p" to open the poem vimwiki directory
    alias p="vim ~/files/poem/poem/index.md"
## "s" to open the website vimwiki directory
    alias s="vim ~/files/site/index.md"
## "r" and "rd" to open sketch docs
    alias r="vim ~/files/org/rascunho.md -c"
    alias rd="vim ~/files/org/dev/rascunho.md"
## "b" or "bib" to open the list of books
    alias bib="vim ~/files/nerd/bib"
    alias b="bib"
## "docs" to open list of documentations
    alias docs="vim ~/files/nerd/doc/doc/settings/docs.md -c"
## "cert" to open list of certifications
    alias cert="vim ~/files/nerd/cert/info.md -c"

# OTHER
## "site" to sync site files and push them to the website
    function site(){
        cv_dir=$HOME/files/nerd/cv/
        cv=$(find $cv_dir -type f -name "*.md")
        for f in ${cv[@]}; do
            echo "Converting $f to .pdf..."
            cvt -mmd -pdf $f
            g=$(basename $f .md)
            mv $g.pdf $cv_dir
        done
        sudo rsync -av --progress --delete $HOME/files/nerd/cv/ $HOME/files/site/md/edu/curriculum/
        sudo rsync -av --progress --delete $HOME/files/nerd/doc/doc/ $HOME/files/site/md/doc/
        sudo rsync -av --progress --delete $HOME/files/nerd/doc/lec/ $HOME/files/site/md/lec/
        sudo rsync -av --progress --delete $HOME/files/nerd/doc/proj/ $HOME/files/site/md/dev/proj/
        sw -c site --toc
        sw -p site
    }
## "poem" to sync poem files and push them to the poem website
    function poem(){
        sudo rsync -av --progress --delete $HOME/files/poem/poem/ $HOME/files/poem/site/md/indice/
        sw -c poem
        sw -p poem
    }
## unzip files to post directories  
    function post(){
        format[0]=insta
        format[1]=lnkd
        format[2]=reels
        N=(0 1 2)
        dir[0]=~/files/poem/insta/posts
        dir[1]=~/files/nerd/lnkd/posts
        dir[2]=~/files/poem/insta/reels
        downloaddir=~/tmp
        function aux(){
            if [[ -f "$downloaddir/${format[$i]}_$1.png" ]]; then
                echo "identified a single .png file..."
                echo "moving to \"${dir[$i]}/$1/\"..."
                mv $downloaddir/${format[$i]}_$1.png ${dir[$i]}/$1/$1.png
                echo "Done!"
            elif [[ -f "$downloaddir/${format[$i]}_$1.zip" ]]; then
                echo "identified a .zip file..."
                echo "extracting in \"${dir[$i]}/$1/\"..."
                unzip $downloaddir/${format[$i]}_$1 -d ${dir[$i]}/$1
                echo "excluding \"${format[$i]}_$1.zip\"..."
                rm $downloaddir/${format[$i]}_$1.zip
                echo "Done!"
            fi
        }
        for i in ${!N[@]}; do
            if [[ "$1" == "${format[$i]}" ]]; then
                if [[ -d ${dir[$i]}/$2 ]]; then
                    echo  "${dir[$i]}/$2 already exists. Subscribe? (y/n)"
                    read -e -p "> " subscribe
                    if [[ "$subscribe" == "y" ]]; then
                        echo "removing old files..."
                        rm -r ${dir[$i]}/$2
                        aux $2
                    else
                        return
                    fi
                else
                    echo "creating dir \"${dir[$i]}/$2\"..."
                    mkdir ${dir[$i]}/$2
                    aux $2
                fi
            fi
        done
        unset -f aux
    }

